# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="GNU GPLv3"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/Fakerac/Baleful/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="baleful" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="1.16.4-0.1.0" #mandatory
 # A display name for the mod
displayName="Baleful" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="https://github.com/Fakerac/Baleful" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="http://example.com/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="examplemod.png" #optional
# A text field displayed in the mod UI
credits="Fakerac, SeaOfPixels"
# A text field displayed in the mod UI
authors="Fakerac" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
§cBaleful §fis a mod adding in multiple features into Vanilla Minecraft, new dungeons, monsters, animals and quality of life improvements.
'''
